### ISSUE TITLE
upload in player

### ISSUE THREAD

**Issue by flourigh** [Paratii-Video/wiki#19]
how to upload vídeo in player.paratii.video?

**Comment by jellegerbrandy** [comment]
You cannot yet. But we are working on it!
Meanwhile, you can register here, and we will contact you as soon as we have the functionality ready:
https://docs.google.com/forms/d/13neNk4DRE3AxofLhQFb7kidPM-8g5QmxMVumrezrE7Y/viewform?edit_requested=true
