### ISSUE TITLE
Model for metadata storage (IPDB)

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/wiki#4]
We need to devise an efficient way to organize and store metadata. Some useful [cost estimates for IPDB can be found here](https://medium.com/ipdb-blog/forever-isnt-free-the-cost-of-storage-on-a-blockchain-database-59003f63e01). We might probably use it. Important to consider native data structures in IPFS / IPDB and the [Coala IP protocol](https://github.com/Paratii-Video/wiki/wiki/Paratii-Blueprint#iiid-content-policy--rights) (designed upon IPLD namespaces) for representing licenses and attribution information. Proposals can come as early drafts still.

**Comment by jellegerbrandy** [comment]
We definitely would benefit from using an existing standard for registering and claiming IP. 

Coala IP seems the right candidate. Coala IP is not in any usable state at all though. It is mostly an abastract specification for structuring data.  There is a siple music-focused js library https://github.com/COALAIP/js-coalaip that in theory we could build upon.

 But what we need as well is not just an abstract ontology for IP, but also ways of populating it: in particular, not just ways of stroing a license, but optoins for licensing as well. 

Ujo music mentions in some blog posts that it is using/developing it (something called "constellate"), which is a very good sign. E.g. https://blog.ujomusic.com/ujo-x-rac-under-the-hood-the-future-of-licensing-d4f38e2efabd they write "COALA IP forms part of the CBOR IPLD specification that will allow us to in the future traverse this graph from metadata object right into Ethereum and other merkle data structures"

**Comment by jellegerbrandy** [comment]
IPDB is dead :cry: 
https://ipdb.io "As of January 19th, 2018, IPDB will be shutting down."
