### ISSUE TITLE
"Publisher package"

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/wiki#8]
Explore the concept of a "publisher downloadable package" that comes with `paratii-ipfs`, `paratii-transcoder`, a `creditWallet` account ready for you to enter the debt/credit system and begin supporting anonymous users, and even a payment channel hub implementation at some point.

We can think of offering this to publishers as a way of further engaging and increasing earnings (truly becoming part of the 'backbone' of the thing). They're not going to be left out of the game, it's just going to be a fair one. There's friction, of course, but when it comes to publishers, those who are non-youtube or who are eager to opt in for alternatives already undergo stuff like plugging in ad networks, DSPs, and so on.

👆 An idea along the lines of inviting Vice / NYTimes / to install a 'masternode'.)

**Comment by aeftimia** [comment]
Spec under active development [here](https://github.com/Paratii-Video/wiki/wiki/Publisher-Quickstart).
